TEMPLATE	= app
LANGUAGE	= C++

CONFIG	+= qt warn_on release

HEADERS	+= src/esvn-diff-wrapper.h

SOURCES	+= src/esvn-diff-wrapper.cpp

# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is an application:  

MAKEFILE = esvn-diff-wrapper.mak
target.files = esvn-diff-wrapper
target.path = /usr/bin 
INSTALLS += target 
unix{
  UI_DIR = .ui
  MOC_DIR = .moc
  OBJECTS_DIR = .obj
}
